CREATE TABLE `tb_document_delivery` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `case_id` bigint DEFAULT NULL COMMENT '案件ID',
  `case_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '案号',
  `case_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '案件名称',
  `document_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '文书名称',
  `document_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '文书类型: COURT_NOTICE-法院通知, JUDGMENT-判决书, VERDICT-裁定书, NOTICE-通知书, OTHER-其他',
  `recipient_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '受送达人',
  `recipient_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '受送达人类型: DEBTOR-债务人, CREDITOR-债权人, LAWYER-律师, COURT-法院, OTHER-其他',
  `contact_phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '联系电话',
  `delivery_address` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '送达地址',
  `delivery_method` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '送达方式: POST-邮寄, EMAIL-邮件, EXPRESS-快递, IN_PERSON-当面送达, ELECTRONIC-电子送达, OTHER-其他',
  `send_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '发送状态: PENDING-待发送, SENT-已发送,FAILED-发送失败, REJECTED-被拒收，SENDING-发送中',
  `delivery_content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '送达内容（富文本）',
  `document_attachment` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '文书附件路径',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `delivery_time` datetime DEFAULT NULL COMMENT '送达时间',
  `failure_reason` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '失败原因',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_user_id` bigint DEFAULT NULL COMMENT '创建者ID',
  `update_user_id` bigint DEFAULT NULL COMMENT '修改者ID',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除: 0-否, 1-是',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'PENDING' COMMENT '状态: PENDING-待审批，APPROVED-已通过，REJECTED-已驳回''',
  `remark` text COLLATE utf8mb4_bin COMMENT '审批意见',
  PRIMARY KEY (`id`),
  KEY `idx_case_id` (`case_id`),
  KEY `idx_case_number` (`case_number`),
  KEY `idx_send_status` (`send_status`),
  KEY `idx_document_type` (`document_type`),
  KEY `idx_recipient_type` (`recipient_type`),
  KEY `idx_delivery_method` (`delivery_method`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_status` (`status`),
  CONSTRAINT `fk_document_delivery_case` FOREIGN KEY (`case_id`) REFERENCES `tb_bankrupt_case` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='文书送达表';




CREATE TABLE `tb_approval` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `case_id` bigint NOT NULL COMMENT '案件ID',
  `lawyer_id` bigint NOT NULL COMMENT '律师ID',
  `approval_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '审核类型: CASE_SUBMIT-案件提交, CASE_CLOSE-案件结案, FEE_APPLY-费用申请, EVIDENCE_UPLOAD-证据上传',
  `approval_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'PENDING' COMMENT '审核状态: PENDING-待审核, APPROVED-已通过, REJECTED-已拒绝, CANCELLED-已取消',
  `approval_title` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '审核标题',
  `approval_content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '审核内容',
  `approval_attachment` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '审核附件',
  `approval_result` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '审核结果: PASS-通过, FAIL-未通过',
  `approval_count` int DEFAULT '0' COMMENT '审核次数',
  `approver_id` bigint DEFAULT NULL COMMENT '审核人ID',
  `approval_date` datetime DEFAULT NULL COMMENT '审核日期',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_user_id` bigint DEFAULT NULL COMMENT '创建者ID',
  `update_user_id` bigint DEFAULT NULL COMMENT '修改者ID',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除: 0-否, 1-是',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE-激活, INACTIVE-停用',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_case_type` (`case_id`,`approval_type`),
  KEY `idx_lawyer_id` (`lawyer_id`),
  KEY `idx_approval_status` (`approval_status`),
  KEY `idx_approver_id` (`approver_id`),
  KEY `idx_approval_date` (`approval_date`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='审批管理表';
